import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "F-Veto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-900 text-white">{children}</body>
      <Analytics />
    </html>
  );
}
