export const equipmentMap = {
  "Glock-18": "glock",
  "USP-S": "usp_silencer",
  P2000: "hkp2000",
  "Dual Berettas": "elite",
  P250: "p250",
  "Tec-9": "tec9",
  "Five-SeveN": "fiveseven",
  "CZ75-Auto": "cz75a",
  "Desert Eagle": "deagle",
  "R8 Revolver": "revolver",

  "Decoy Grenade": "decoy",
  Flashbang: "flashbang",
  "High Explosive Grenade": "hegrenade",
  Molotov: "molotov",
  "Smoke Grenade": "smokegrenade",
  "Incendiary Grenade": "incgrenade",

  AWP: "awp",
  G3SG1: "g3sg1",
  "SCAR-20": "scar20",
  "SSG 08": "ssg08",
  "MAC-10": "mac10",
  "MP5-SD": "mp5sd",
  "UMP-45": "ump45",
  MP7: "mp7",
  MP9: "mp9",
  "PP-Bizon": "bizon",
  P90: "p90",
  "AK-47": "ak47",
  AUG: "aug",
  FAMAS: "famas",
  "Galil AR": "galilar",
  "M4A1-S": "m4a1_silencer",
  M4A4: "m4a1",
  "SG 553": "sg556",
  "MAG-7": "mag7",
  Negev: "negev",
  "Sawed-Off": "sawedoff",
  Nova: "nova",
  M249: "m249",
  XM1014: "xm1014",

  C4: "c4",
};
